stop_words = ['dey', 'awfar', 'wey', 'wan', 'shey', 'sabi', 'i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves',
              'you', 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'chop', 'beta', 'molenu', 
              'his', 'himself', 'she', 'her', 'hers', 'herself', 'it', 'its','eni', 'duro',
              'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'dia', 'moti', 'gba',
              'what', 'which', 'who', 'whom', 'this', 'that', 'these', 'mo', 'lenu', 'ewo', 'chai',
              'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'e', 'don', 'oshe', 'oshey',
              'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'hussle', 'hashtag',
              'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'werey', 'unda', 'khaki',
              'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'awon', 'ja', 'eja',
              'against', 'between', 'into', 'through', 'during', 'before', 'after', 'tenk', '10x', 
              'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'oshi', 'belle', 'casala',
              'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here',
              'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each',
              'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not',
              'only', 'own', 'same', 'so', 'than', 'too', 'very', 's', 't', 'can',
              'will', 'just', 'don','should', 'now','https',"'s",'...', "whats'",
              "rt","whats","n't","de","'m","un","en","dedic","twittermoments",
              "amp","e","y","o","ce","retweet","sur","na","el","1","2","3","4",
              "5","6","7","8","9","0","ca","nao","se","com","los","u","des","-",
              "--","'","''","la","como","con","segundo",'de', 'la', 'que', 'el',
              'en', 'y', 'a', 'los', 'del', 'se', 'las', 'por', 'un', 'para',
              'con', 'no', 'una', 'su', 'al', 'lo',
              'le', 'ya', 'o', "know","time","q","em", 'fent', 'kalamity', 'wine',
              "re","11","isnt","wan","ver","like","'re","m","'ve","bec","n","twt","kca","c","a",
              "b","d","e","f","g","h","i","j","k","l","m","n","o",
              "p","q","r","s","t","u","v","w","x","y","z"]
